In [41]:
import numpy as np

In [1]:
import pandas as pd

# Load the CSV

attackMode = "Lan"
#attackMode = "Vis"
df = pd.read_csv(f"/data1/chethan/spectralShift/gemma_attack/outputsStorageImagenet/backUp/alignment_shift_sweep{attackMode}.csv")



# Inspect it

print(df.head())

print(df.shape)

print(df.columns)

  AttackMode  VisionLayerTrack  LanLayerTrack  HistogramIndex  L2 Distance  \
0        lan                 0              0               0     1.352724
1        lan                 0              0               1     1.352861
2        lan                 0              0               2     1.352737
3        lan                 0              0               3     0.002616
4        lan                 0              0               4     0.001935

   Mean Absolute Difference  Maximum Change  COM Shift  Sign Shift
0                  0.006561        0.123535  -6.229879   -0.000122
1                  0.006346        0.093018 -94.554061   -0.000222
2                  0.006333        0.090271 -39.989465   -0.000161
3                  0.000140        0.000377  11.786717    0.000131
4                  0.000096        0.000407   1.119659    0.000084
(174, 9)
Index(['AttackMode', 'VisionLayerTrack', 'LanLayerTrack', 'HistogramIndex',
       'L2 Distance', 'Mean Absolute Difference', 'Maximum Change',
       'COM Shift', 'Sign Shift'],
      dtype='object')

In [2]:
point_labels = [
"query proj", "key proj", "value proj", "att output proj",
"MLP exp", "MLP out proj", "Vis-to-lan proj", "query proj",
"key proj", "value proj", "MLP gate proj", "MLP up proj",
"MLP down proj"
]



if attackMode == "Vis":
    #point_labels = point_labels[:7]
    point_labels = point_labels[:6]
else:
    #point_labels = point_labels[6:]
    point_labels = point_labels[7:]

In [3]:
point_labels

['query proj',
 'key proj',
 'value proj',
 'MLP gate proj',
 'MLP up proj',
 'MLP down proj']

In [4]:
df['HistogramIndex'] = df['HistogramIndex'].map(dict(enumerate(point_labels)))

In [5]:
df

,AttackMode,VisionLayerTrack,LanLayerTrack,HistogramIndex,L2 Distance,Mean Absolute Difference,Maximum Change,COM Shift,Sign Shift
0,lan,0,0,query proj,1.352724,0.006561,0.123535,-6.229879,-0.000122
1,lan,0,0,key proj,1.352861,0.006346,0.093018,-94.554061,-0.000222
2,lan,0,0,value proj,1.352737,0.006333,0.090271,-39.989465,-0.000161
3,lan,0,0,MLP gate proj,0.002616,0.000140,0.000377,11.786717,0.000131
4,lan,0,0,MLP up proj,0.001935,0.000096,0.000407,1.119659,0.000084
...,...,...,...,...,...,...,...,...,...
169,lan,0,26,key proj,0.893642,0.004263,0.061157,172.690667,-0.000127
170,lan,0,26,value proj,0.893683,0.004137,0.063354,174.854362,-0.000132
171,lan,0,26,MLP gate proj,0.002018,0.000093,0.000477,7.948841,-0.000081
172,lan,0,26,MLP up proj,0.001965,0.000094,0.000367,6.694023,0.000065
173,lan,0,26,MLP down proj,0.000718,0.000039,0.000145,23.602980,-0.000036

In [6]:
exclude = [
    'query proj',
    'key proj',
    'value proj'
]

df_filtered = df[~df['HistogramIndex'].isin(exclude)]

In [7]:
df_filtered[['L2 Distance']].sort_values(by='L2 Distance', ascending=False)

     L2 Distance
93      0.007030
82      0.006540
117     0.006406
124     0.006361
76      0.004975
..           ...
167     0.000376
161     0.000359
119     0.000355
131     0.000342
155     0.000313

[87 rows x 1 columns]

In [8]:
df_filtered[['Mean Absolute Difference']].sort_values(by='Mean Absolute Difference', ascending=False)

     Mean Absolute Difference
93                   0.000393
82                   0.000372
117                  0.000366
124                  0.000362
76                   0.000278
..                        ...
47                   0.000017
161                  0.000017
131                  0.000015
119                  0.000015
155                  0.000014

[87 rows x 1 columns]

In [9]:
df_filtered[['Maximum Change']].sort_values(by='Maximum Change', ascending=False)

     Maximum Change
142        0.001021
57         0.001007
94         0.000916
154        0.000820
40         0.000805
..              ...
53         0.000103
155        0.000100
47         0.000097
131        0.000087
161        0.000073

[87 rows x 1 columns]

In [10]:
df_filtered[['COM Shift']].sort_values(by='COM Shift', ascending=False)

     COM Shift
125  67.889600
69   52.171080
147  41.376856
64   39.697035
83   38.283332
..         ...
35  -33.942508
82  -36.526304
159 -38.059317
142 -45.663548
70  -46.032960

[87 rows x 1 columns]

In [11]:
df_filtered.loc[125]

AttackMode                            lan
VisionLayerTrack                        0
LanLayerTrack                          18
HistogramIndex              MLP down proj
L2 Distance                      0.000784
Mean Absolute Difference         0.000042
Maximum Change                    0.00013
COM Shift                         67.8896
Sign Shift                       0.000041
Name: 125, dtype: object

In [12]:
df_filtered.loc[70]

AttackMode                          lan
VisionLayerTrack                      0
LanLayerTrack                         9
HistogramIndex              MLP up proj
L2 Distance                    0.004494
Mean Absolute Difference       0.000252
Maximum Change                 0.000539
COM Shift                     -46.03296
Sign Shift                     0.000238
Name: 70, dtype: object

In [13]:
df_filtered.loc[93]

AttackMode                            lan
VisionLayerTrack                        0
LanLayerTrack                          13
HistogramIndex              MLP gate proj
L2 Distance                       0.00703
Mean Absolute Difference         0.000393
Maximum Change                   0.000737
COM Shift                       -9.498203
Sign Shift                      -0.000378
Name: 93, dtype: object

In [14]:
df_weak_cs_strong = pd.read_csv(f"/data1/chethan/spectralShift/gemma_attack/OverlapDistancesAvg/weak_vs_strong_l2_summary.csv")

df_weak_cs_strong.head()

,LanLayerTrack,VisionLayerTrack,attackMode,point_label,weak_vs_strong_l2_distance
0,0,0,lan,query proj,2.513608
1,0,0,vis,query proj,0.068755
2,0,0,lan,key proj,2.513058
3,0,0,vis,key proj,0.068912
4,0,0,lan,value proj,2.513584

In [15]:
print(df_weak_cs_strong['point_label'].unique())

['query proj ' 'query proj' 'key proj ' 'key proj' 'value proj '
 'value proj' 'MLP gate proj' 'MLP up proj' 'MLP down proj'
 'att output proj' 'MLP exp' 'MLP out proj']

In [16]:
exclude = ['query proj ', 'key proj ', 'value proj ']

df_weak_cs_strong = df_weak_cs_strong[
    ~df_weak_cs_strong['point_label'].isin(exclude)
]

In [17]:
df_weak_cs_strong.head()

,LanLayerTrack,VisionLayerTrack,attackMode,point_label,weak_vs_strong_l2_distance
1,0,0,vis,query proj,0.068755
3,0,0,vis,key proj,0.068912
5,0,0,vis,value proj,0.068610
6,0,0,lan,MLP gate proj,0.301197
7,0,0,lan,MLP up proj,0.301169

In [18]:
df_weak_cs_strong[['weak_vs_strong_l2_distance']].sort_values(by='weak_vs_strong_l2_distance', ascending=False)

    weak_vs_strong_l2_distance
30                    0.321238
29                    0.321238
18                    0.303105
17                    0.303102
6                     0.301197
7                     0.301169
37                    0.265224
34                    0.210325
8                     0.182190
32                    0.174726
27                    0.174715
25                    0.174693
19                    0.173009
31                    0.155345
35                    0.129624
20                    0.106067
15                    0.106016
13                    0.105995
33                    0.091172
22                    0.090553
21                    0.074719
3                     0.068912
1                     0.068755
5                     0.068610
23                    0.058841
10                    0.052517
11                    0.034091
9                     0.011797

In [19]:
df_weak_cs_strong.iloc[16]

LanLayerTrack                        0
VisionLayerTrack                     1
attackMode                         vis
point_label                    MLP exp
weak_vs_strong_l2_distance    0.090553
Name: 22, dtype: object